/* Generated by tools/make_shadow.py - do not edit. */
#ifndef SHADOW_H
#define SHADOW_H

#define SHADOW_TILES_W 3
#define SHADOW_TILES_H 1
#define SHADOW_TILE_COUNT 3
#define SHADOW_PX_W 48
#define SHADOW_PX_H 16

/* 16 colours, index 0 transparent; only index 1 is drawn. */
static const u16 shadow_palette[16] = {
    0x8000, 0x1110, 0x8000, 0x8000,
    0x8000, 0x8000, 0x8000, 0x8000,
    0x8000, 0x8000, 0x8000, 0x8000,
    0x8000, 0x8000, 0x8000, 0x8000,
};

#endif
