/* Generated by tools/make_spark.py - do not edit. */
#ifndef SPARK_H
#define SPARK_H

#define SPARK_FRAMES 3
#define SPARK_TILES_W 1
#define SPARK_TILES_H 1
#define SPARK_TILE_COUNT 3
#define SPARK_PX_W 16
#define SPARK_PX_H 16

/* 16 colours, index 0 transparent. */
static const u16 spark_palette[16] = {
    0x8000, 0xe611, 0xbd51, 0x2fa3,
    0x6fea, 0x8000, 0x8000, 0x8000,
    0x8000, 0x8000, 0x8000, 0x8000,
    0x8000, 0x8000, 0x8000, 0x8000,
};

#endif
