/* Generated by tools/stage2neo.py - do not edit. */
#ifndef STAGE_H
#define STAGE_H

#define STAGE_COLS 20

/* The floor plane: screen y of depth 0, and how many
   scanlines of depth there are. Feet at depth z land on
   screen line STAGE_FLOOR_TOP + z.

   FLOOR_BACK is how much of that floor sits behind the
   furthest a character may stand, so the back row has
   ground behind its feet instead of the horizon. Depth is
   therefore clamped to FLOOR_BACK..FLOOR_DEPTH-1, not to
   0..FLOOR_DEPTH-1. */
#define STAGE_FLOOR_TOP 128
#define STAGE_FLOOR_DEPTH 72
#define STAGE_FLOOR_BACK 16

#define STAGE_SKY_Y 0
#define STAGE_SKY_ROWS 8
#define STAGE_SKY_TILE_COUNT 160
#define STAGE_HILLS_Y 64
#define STAGE_HILLS_ROWS 4
#define STAGE_HILLS_TILE_COUNT 80
#define STAGE_GROUND_Y 128
#define STAGE_GROUND_ROWS 6
#define STAGE_GROUND_TILE_COUNT 120

/* 16 colours, index 0 transparent. */
static const u16 stage_palette[16] = {
    0x8000, 0xf766, 0xf456, 0xd543,
    0xd344, 0x5258, 0x0246, 0x4234,
    0x5135, 0x4223, 0x6113, 0x0124,
    0x0112, 0xf013, 0x2003, 0x0002,
};

#endif
