/* Generated by tools/make_stage.py - do not edit. */
#ifndef STAGE_H
#define STAGE_H

#define STAGE_COLS 20

/* The walkable floor plane: screen y of depth 0, and how
   many scanlines of depth there are. Feet at depth z land
   on screen line STAGE_FLOOR_TOP + z. */
#define STAGE_FLOOR_TOP 128
#define STAGE_FLOOR_DEPTH 72

#define STAGE_SKY_Y 0
#define STAGE_SKY_ROWS 8
#define STAGE_SKY_TILE_COUNT 160
#define STAGE_HILLS_Y 64
#define STAGE_HILLS_ROWS 4
#define STAGE_HILLS_TILE_COUNT 80
#define STAGE_GROUND_Y 128
#define STAGE_GROUND_ROWS 6
#define STAGE_GROUND_TILE_COUNT 120

/* 16 colours, index 0 transparent. */
static const u16 stage_palette[16] = {
    0x8000, 0x9112, 0x7113, 0x2325,
    0xd446, 0x2edc, 0x7001, 0xe113,
    0x3112, 0xa211, 0x3321, 0xf432,
    0xa643, 0x3100, 0x4232, 0x2864,
};

#endif
