#!/usr/bin/env python3
"""Draw the spark that flashes where a blow lands, as sprite tiles.

A starburst is geometry rather than draughtsmanship - spikes radiating from a
centre - so it is cheaper to describe than to draw, and describing it means
the animation costs nothing: the frames are the same shape at different radii.

Each frame is one 16x16 tile, which is one sprite. That is small for a
starburst, so it is drawn for contrast rather than for detail: a dark rim all
the way round so it reads against the pale floor and the night sky alike, then
bright yellow spikes, then a dark core where the blow actually landed.

The shape is evaluated per pixel rather than drawn with a polygon. At this
size a polygon rasteriser spends its time on antialiasing decisions that get
quantised away, and the spike tips come out mushy; solving the star's radius
at each pixel's angle puts a hard edge exactly where it belongs.
"""

import argparse
import math

from neogeo_color import to_color_word

from PIL import Image

# Index 0 is transparent on this hardware, so the art starts at 1. Taken off
# the reference: a dark rim, two yellows and an amber between them, and a
# near-black centre.
PALETTE = [
    (0, 0, 0),          # 0  transparent, never drawn
    (104, 24, 16),      # 1  rim, and the core
    (216, 88, 24),      # 2  amber
    (248, 176, 48),     # 3  yellow
    (255, 240, 160),    # 4  pale yellow, the hottest part
]

# Each frame is (outer radius, how sharp the spikes are, how hollow the
# middle is). The blow flashes open, reaches full size, then burns out from
# the inside - which reads as dissipating rather than simply shrinking.
FRAMES = [
    (4.6, 1.6, 0.00),
    (7.4, 2.2, 0.00),
    (7.4, 3.2, 0.55),
]

SPIKES = 8

# Alternate spikes are slightly shorter. A star whose points are all one
# length reads as a cog rather than an impact. Much below this and the short
# spikes stop touching the long ones and break off into detached dots.
SHORT_SPIKE = 0.85

# Turned half a spike off the axes. Axis-aligned points put the four longest
# spikes flat against the edges of the cell, where they read as a plus sign;
# offsetting them makes the same shape look like a burst.
ROTATION = math.pi / 8


def draw_frame(size, outer, sharpness, hollow):
    im = Image.new("P", (size, size), 0)
    im.putpalette([c for rgb in PALETTE for c in rgb] + [0, 0, 0] * (16 - len(PALETTE)))

    centre = (size - 1) / 2.0
    inner = outer * 0.34

    for y in range(size):
        for x in range(size):
            dx, dy = x - centre, y - centre
            r = math.hypot(dx, dy)
            if r < 0.001:
                im.putpixel((x, y), 1)
                continue

            # The star's radius at this angle. cos peaks once per spike, and
            # raising it to a power narrows the spike towards its tip.
            a = math.atan2(dy, dx) + ROTATION
            t = abs(math.cos(SPIKES * a / 2.0)) ** sharpness

            # Which spike this angle belongs to, so every other one can be
            # cut short. Lobes are one SPIKES-th of a turn apart.
            lobe = int(round(a / (2.0 * math.pi / SPIKES))) % SPIKES
            reach = outer if lobe % 2 == 0 else inner + (outer - inner) * SHORT_SPIKE

            edge = inner + (reach - inner) * t
            if r > edge:
                continue

            f = r / edge                # 0 at the centre, 1 at the spike tip
            if f < hollow:
                continue                # burnt out from the middle
            if f > 0.86:
                im.putpixel((x, y), 1)  # rim
            elif f > 0.55:
                im.putpixel((x, y), 3)
            elif f > 0.30:
                im.putpixel((x, y), 4)
            elif f > 0.16:
                im.putpixel((x, y), 2)
            else:
                im.putpixel((x, y), 1)  # the dark centre of the impact
    return im


def write_header(path, name, size, frames):
    up = name.upper()
    words = [0x8000] + [to_color_word(*c) for c in PALETTE[1:]]
    words += [0x8000] * (16 - len(words))

    with open(path, "w") as f:
        f.write("/* Generated by tools/make_spark.py - do not edit. */\n")
        f.write(f"#ifndef {up}_H\n#define {up}_H\n\n")
        f.write(f"#define {up}_FRAMES {frames}\n")
        f.write(f"#define {up}_TILES_W 1\n")
        f.write(f"#define {up}_TILES_H 1\n")
        # One tile per frame, laid out left to right, so frame f is tile f.
        f.write(f"#define {up}_TILE_COUNT {frames}\n")
        # Not {up}_W and {up}_H: {up}_H is this header's own include guard.
        f.write(f"#define {up}_PX_W {size}\n")
        f.write(f"#define {up}_PX_H {size}\n\n")
        f.write("/* 16 colours, index 0 transparent. */\n")
        f.write(f"static const u16 {name}_palette[16] = {{\n")
        for i in range(0, 16, 4):
            f.write("    " + ", ".join(f"0x{w:04x}" for w in words[i:i + 4]) + ",\n")
        f.write("};\n\n#endif\n")


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("-o", "--output", required=True, help="GIF to write")
    p.add_argument("--header", required=True, help="C header to write")
    p.add_argument("--name", default="spark", help="identifier prefix")
    p.add_argument("--size", type=int, default=16, help="cell size, whole tiles")
    p.add_argument("--preview", metavar="PNG",
                   help="also write a magnified sheet, for looking at")
    args = p.parse_args()

    if args.size % 16:
        raise SystemExit("error: --size must be a whole number of 16 px tiles")

    sheet = Image.new("P", (args.size * len(FRAMES), args.size), 0)
    sheet.putpalette([c for rgb in PALETTE for c in rgb]
                     + [0, 0, 0] * (16 - len(PALETTE)))
    for i, (outer, sharpness, hollow) in enumerate(FRAMES):
        scale = args.size / 16.0
        sheet.paste(draw_frame(args.size, outer * scale, sharpness, hollow),
                    (i * args.size, 0))

    # optimize=False, or Pillow drops the unused index 0 and shifts every
    # colour down one - and index 0 is transparent on this hardware.
    sheet.save(args.output, transparency=0, optimize=False)
    write_header(args.header, args.name, args.size, len(FRAMES))

    if args.preview:
        sheet.convert("RGB").resize(
            (sheet.width * 12, sheet.height * 12), Image.NEAREST
        ).save(args.preview)

    print(f"{args.output}: {len(FRAMES)} frames of {args.size}x{args.size} px, "
          f"1 tile each")


if __name__ == "__main__":
    main()
