#!/usr/bin/env python3
"""Draw the shadow that sits under a character, and emit it as a sprite tile.

A jump is unreadable without one. With the character's size fixed at every
depth, nothing on screen distinguishes "standing at the back of the floor"
from "in the air at the front" except a shadow staying behind on the ground.

The hardware has no alpha and no blending: a sprite pixel is either a palette
colour or transparent. So the shadow is stippled rather than translucent - a
checkerboard of one dark colour, which the eye and a CRT average into a tint
of whatever it is drawn over. A solid blob reads as a hole in the floor
instead, which is why this is worth the trouble.

The core is solid and only the outer part is stippled, because a shadow that
is checkerboard all the way through shimmers as the floor scrolls underneath
it.
"""

import argparse

from neogeo_color import to_color_word
from PIL import Image, ImageDraw

# Index 0 is transparent on this hardware, so the shadow itself is index 1.
SHADOW_RGB = (20, 15, 12)


def draw_shadow(w, h, thickness):
    """An ellipse filling the cell's width, centred in its height."""
    im = Image.new("P", (w, h), 0)
    im.putpalette([0, 0, 0] + list(SHADOW_RGB) + [0, 0, 0] * 14)

    cx, cy = (w - 1) / 2.0, (h - 1) / 2.0
    rx, ry = w / 2.0, thickness / 2.0

    for y in range(h):
        for x in range(w):
            # Normalised distance from the centre: 1.0 is the edge.
            dx = (x - cx) / rx
            dy = (y - cy) / ry
            d = dx * dx + dy * dy
            if d > 1.0:
                continue
            # Solid within the core, stippled out to the edge.
            if d <= 0.45 or (x + y) % 2 == 0:
                im.putpixel((x, y), 1)
    return im


def write_header(path, name, im, tiles_w, tiles_h):
    up = name.upper()
    words = [0x8000] + [to_color_word(*SHADOW_RGB)] + [0x8000] * 14

    with open(path, "w") as f:
        f.write("/* Generated by tools/make_shadow.py - do not edit. */\n")
        f.write(f"#ifndef {up}_H\n#define {up}_H\n\n")
        f.write(f"#define {up}_TILES_W {tiles_w}\n")
        f.write(f"#define {up}_TILES_H {tiles_h}\n")
        f.write(f"#define {up}_TILE_COUNT {tiles_w * tiles_h}\n")
        # Not {up}_W and {up}_H: {up}_H is this header's own include guard.
        f.write(f"#define {up}_PX_W {im.width}\n")
        f.write(f"#define {up}_PX_H {im.height}\n\n")
        f.write("/* 16 colours, index 0 transparent; only index 1 is drawn. */\n")
        f.write(f"static const u16 {name}_palette[16] = {{\n")
        for i in range(0, 16, 4):
            f.write("    " + ", ".join(f"0x{w:04x}" for w in words[i:i + 4]) + ",\n")
        f.write("};\n\n#endif\n")


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("-o", "--output", required=True, help="GIF to write")
    p.add_argument("--header", required=True, help="C header to write")
    p.add_argument("--name", default="shadow", help="identifier prefix")
    p.add_argument("--width", type=int, default=48,
                   help="whole tiles wide; a character is 56 px across")
    p.add_argument("--height", type=int, default=16, help="cell height")
    p.add_argument("--thickness", type=int, default=11,
                   help="how tall the ellipse itself is within the cell")
    args = p.parse_args()

    if args.width % 16 or args.height % 16:
        raise SystemExit("error: --width and --height must be whole tiles of 16")
    if args.thickness > args.height:
        raise SystemExit("error: --thickness must fit inside --height")

    im = draw_shadow(args.width, args.height, args.thickness)
    # optimize=False, or Pillow drops the unused index 0 and shifts every
    # colour down one - and index 0 is transparent on this hardware.
    im.save(args.output, transparency=0, optimize=False)

    tiles_w, tiles_h = args.width // 16, args.height // 16
    write_header(args.header, args.name, im, tiles_w, tiles_h)
    print(f"{args.output}: {args.width}x{args.height} px = "
          f"{tiles_w}x{tiles_h} tiles")


if __name__ == "__main__":
    main()
