;;; Sound commands for the Z80.
;;;
;;; The 68000 cannot touch the sound chip: it writes a single byte to
;;; REG_SOUND and that fires an NMI on the Z80, which looks the byte up in the
;;; table below and runs the matching routine. So every sound the game can
;;; make is one entry here, and the 68000 side is just a number.
;;;
;;; Commands 0 to 3 are reserved by nullsound. Ours start at 4 and must stay
;;; in step with the SND_* values in src/sound.h.

        .include "helpers.inc"
        .area   CODE

cmd_jmptable::
        ;; reserved by the driver
        jp      snd_command_unused
        jp      snd_command_01_prepare_for_rom_switch
        jp      snd_command_unused
        jp      snd_command_03_reset_driver
        ;; ours
        jp      play_gong
        jp      play_jump
        jp      play_punch
        jp      play_taiko
        jp      play_koto
        init_unused_cmd_jmptable


play_gong:
        ld      ix, #adpcm_a_gong
        call    snd_adpcm_a_play
        ret

play_jump:
        ld      ix, #adpcm_a_jump
        call    snd_adpcm_a_play
        ret

play_punch:
        ld      ix, #adpcm_a_punch
        call    snd_adpcm_a_play
        ret

play_taiko:
        ld      ix, #adpcm_a_taiko
        call    snd_adpcm_a_play
        ret

play_koto:
        ld      ix, #adpcm_a_koto
        call    snd_adpcm_a_play
        ret


;;; Where each sample sits in the sample ROM, generated by vromtool.
        .include "assets/samples.inc"

;;; One descriptor per sample: start and stop offset in the V ROM, which of
;;; the six ADPCM-A channels to use, and the volume with both speakers on.
;;;
;;; The effects are on separate channels so they can overlap - landing a punch
;;; while still in the air should not cut the jump short.
;;;
;;; The two pieces of music deliberately share channel 4. Starting a channel
;;; that is already playing restarts it on the new sample, so the screen's
;;; music replaces the previous screen's rather than playing over the top of
;;; it, and no separate "stop" command is needed.

adpcm_a_gong:
        .db     GONG_START_LSB
        .db     GONG_START_MSB
        .db     GONG_STOP_LSB
        .db     GONG_STOP_MSB
        .db     0                       ; channel 1
        .db     0xdf                    ; left and right, full volume
        .db     1                       ; channel 1, as a bit

adpcm_a_jump:
        .db     JUMP_START_LSB
        .db     JUMP_START_MSB
        .db     JUMP_STOP_LSB
        .db     JUMP_STOP_MSB
        .db     1                       ; channel 2
        .db     0xdf
        .db     2

adpcm_a_punch:
        .db     PUNCH_START_LSB
        .db     PUNCH_START_MSB
        .db     PUNCH_STOP_LSB
        .db     PUNCH_STOP_MSB
        .db     2                       ; channel 3
        .db     0xdf
        .db     4

adpcm_a_taiko:
        .db     TAIKO_START_LSB
        .db     TAIKO_START_MSB
        .db     TAIKO_STOP_LSB
        .db     TAIKO_STOP_MSB
        .db     3                       ; channel 4, the music channel
        .db     0xdb                    ; a little under the effects
        .db     8

adpcm_a_koto:
        .db     KOTO_START_LSB
        .db     KOTO_START_MSB
        .db     KOTO_STOP_LSB
        .db     KOTO_STOP_MSB
        .db     3                       ; channel 4, the music channel
        .db     0xdb
        .db     8
